### ISSUE TITLE
Dataset of amazon-product

### ISSUE THREAD

**Issue by rsj123** [giamba95/SaplingSimilarity#1]
Hi,
What is the dataset: amazon-product.
Any refer?

**Comment by giamba95** [comment]
Hi,
all information about the dataset is available at http://jmcauley.ucsd.edu/data/amazon/
In particular, I downloaded the dataset from the GitHub repository: https://github.com/librahu/HIN-Datasets-for-Recommendation-and-Network-Embedding and I utilized a 10-core setting, which means I considered only users and items with at least 10 interactions.

**Comment by rsj123** [comment]
Thanks for your kind
